# Generated by Django 5.1.1 on 2024-10-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_trip_rider_weight_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='rider_weight',
        ),
    ]
