# Generated by Django 5.1.1 on 2024-10-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_trip_rider_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rider_weight',
            field=models.FloatField(default=60),
        ),
    ]
