# Generated by Django 5.1.1 on 2024-10-15 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_remove_trip_rider_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bikemodel',
            old_name='name',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='bike',
            name='vehicle_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='rider_weight',
            field=models.FloatField(default=60),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.bikebrand'),
        ),
    ]
