# Generated by Django 5.1.1 on 2024-10-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_bikebrand_rename_name_bikemodel_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='fuel_efficiency',
            field=models.FloatField(default=40),
        ),
    ]
