# Generated by Django 5.1.1 on 2024-10-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_bikemodel_fuel_efficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='calculated_FE',
            field=models.FloatField(null=True),
        ),
    ]
