# Generated by Django 5.1.1 on 2024-10-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_trip_calculated_fe'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_images/'),
        ),
    ]
