# Generated by Django 5.1.1 on 2024-10-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_bike_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='date_added',
            new_name='last_service_date',
        ),
    ]
