# Generated by Django 5.1.1 on 2024-10-22 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_rename_date_added_bike_last_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
